spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:local;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers_skip_column_definitions: true
        globally_quoted_identifiers: true
        format_sql: true
    defer-datasource-initialization: true
  redis:
    host: localhost
logging:
  level:
    root: info
    org.springframework.cache: DEBUG
cache:
  redis:
    enabled: true
